title: Project Vidyalaya
email: brgclasses@gmail.com
description: >-
  An Open Source solutions for Education.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
twitter_username: coolbrg
github_username:  coolbrg

google_analytics: # your google analytics id

# Build settings
markdown: kramdown
